In [13]:
import torch
import pandas as pd



col = torch.tensor([1, 2, 0, 0, 3])   # 代表 5 條邊的「終點（target / 鄰居）」
list = [0, 1, 2, 3]   

h = torch.tensor([[0.1, 0.2],   # node 0 的特徵
                  [0.3, 0.4],   # node 1 的特徵
                  [0.5, 0.6],   # node 2 的特徵
                  [0.7, 0.8]])  # node 3 的特徵 


print(h[col])    # 根據 col 中的索引，從 h 中選取對應的行，得到每條邊的鄰居特徵
print(h[list])   # 根據 col 中的索引，從 h 中選取對應的行，得到每條邊的鄰居特徵


a = [[0.1, 0.2],   # node 0 的特徵
                  [0.3, 0.4],   # node 1 的特徵
                  [0.5, 0.6],   # node 2 的特徵
                  [0.7, 0.8]]


print(h[0])
print(a[0])
print(a[0][0])


tensor([[0.3000, 0.4000],
        [0.5000, 0.6000],
        [0.1000, 0.2000],
        [0.1000, 0.2000],
        [0.7000, 0.8000]])
tensor([[0.1000, 0.2000],
        [0.3000, 0.4000],
        [0.5000, 0.6000],
        [0.7000, 0.8000]])
tensor([0.1000, 0.2000])
[0.1, 0.2]
0.1
